---
apiVersion: v1
kind: Service
metadata:
  name: stateful-svc
  labels:
    app: stateful-app
spec:
  clusterIP: None  # Makes it headless
  ports:
    - port: 80
  selector:
    app: stateful-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-app
spec:
  serviceName: "stateful-svc"  # Matches headless service
  replicas: 2
  selector:
    matchLabels:
      app: stateful-app
  template:
    metadata:
      labels:
        app: stateful-app
    spec:
      containers:
        - name: alpine
          image: alpine:3.18  # Extremely lightweight (5MB)
          command: ["sleep", "infinity"]  # Keeps pods running
---
apiVersion: v1
kind: Pod
metadata:
  name: dns-checker
spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot:latest  # Popular networking toolkit
      command: ["sleep", "infinity"]